/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 11/02/2011, 10:23:41 AM
 */
package com.py.mbaez.porandu.views;

import com.py.mbaez.porandu.components.AddTabbedHeader;
import com.py.mbaez.porandu.managers.SessionManager;
import com.py.mbaez.porandu.components.ClosableTabbedHeader;
import javax.swing.*;
import jsyntaxpane.DefaultSyntaxKit;

/**
 *
 * @author mbaez
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            DefaultSyntaxKit.initKit();
        } catch (Exception e) {
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        conectarButton = new javax.swing.JButton();
        duplicarConexionButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        guardarScriptButton = new javax.swing.JButton();
        guardarTablaButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        ejecutarButton = new javax.swing.JButton();
        pararButton = new javax.swing.JButton();
        sqlQueryResultTabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        conexionMenuItem = new javax.swing.JMenuItem();
        duplicarConexionMenuItem = new javax.swing.JMenuItem();
        guardarResultadoMenuItem = new javax.swing.JMenuItem();
        guardarMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        acercaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Porandu");

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        conectarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/database_connect.png"))); // NOI18N
        conectarButton.setToolTipText("Nueva Conexión");
        conectarButton.setFocusable(false);
        conectarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conectarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarButtonActionPerformed(evt);
            }
        });
        toolBar.add(conectarButton);

        duplicarConexionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/database_go.png"))); // NOI18N
        duplicarConexionButton.setToolTipText("Duplicar Conexión");
        duplicarConexionButton.setFocusable(false);
        duplicarConexionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        duplicarConexionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        duplicarConexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicarConexionButtonActionPerformed(evt);
            }
        });
        toolBar.add(duplicarConexionButton);
        toolBar.add(jSeparator3);

        guardarScriptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/script_save.png"))); // NOI18N
        guardarScriptButton.setToolTipText("Guardar Script Sql");
        guardarScriptButton.setFocusable(false);
        guardarScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarScriptButtonActionPerformed(evt);
            }
        });
        toolBar.add(guardarScriptButton);

        guardarTablaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/table_save.png"))); // NOI18N
        guardarTablaButton.setToolTipText("Guardar resultado de la consulta");
        guardarTablaButton.setFocusable(false);
        guardarTablaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarTablaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarTablaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTablaButtonActionPerformed(evt);
            }
        });
        toolBar.add(guardarTablaButton);
        toolBar.add(jSeparator2);

        ejecutarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/lightning_go.png"))); // NOI18N
        ejecutarButton.setToolTipText("Ejecutar");
        ejecutarButton.setFocusable(false);
        ejecutarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ejecutarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ejecutarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarButtonActionPerformed(evt);
            }
        });
        toolBar.add(ejecutarButton);

        pararButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/lightning_delete.png"))); // NOI18N
        pararButton.setToolTipText("Parar");
        pararButton.setFocusable(false);
        pararButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pararButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pararButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararButtonActionPerformed(evt);
            }
        });
        toolBar.add(pararButton);

        sqlQueryResultTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        inicioMenu.setText("Inicio");

        conexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        conexionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/database_connect.png"))); // NOI18N
        conexionMenuItem.setText("Nueva Conexion");
        conexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexionMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(conexionMenuItem);

        duplicarConexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        duplicarConexionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/database_go.png"))); // NOI18N
        duplicarConexionMenuItem.setText("Duplicar Conexion");
        duplicarConexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicarConexionMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(duplicarConexionMenuItem);

        guardarResultadoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        guardarResultadoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/table_save.png"))); // NOI18N
        guardarResultadoMenuItem.setText("Exportar Datos");
        guardarResultadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarResultadoMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(guardarResultadoMenuItem);

        guardarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        guardarMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/script_save.png"))); // NOI18N
        guardarMenuItem.setText("Guardar Script");
        guardarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(guardarMenuItem);

        salirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salirMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/delete.png"))); // NOI18N
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(salirMenuItem);

        menuBar.add(inicioMenu);

        ayudaMenu.setText("Ayuda");

        acercaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        acercaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/py/mbaez/porandu/icon/info.png"))); // NOI18N
        acercaMenuItem.setText("Acerca de...");
        acercaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaMenuItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(acercaMenuItem);

        menuBar.add(ayudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sqlQueryResultTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqlQueryResultTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarButtonActionPerformed
        SqlQueryResult panel = (SqlQueryResult) this.sqlQueryResultTabbedPane.getSelectedComponent();
        panel.ejecutarLocalQuery();
    }//GEN-LAST:event_ejecutarButtonActionPerformed

    private void conexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexionMenuItemActionPerformed
        ConexionDialog conexionDialog = new ConexionDialog(this, true);
        conexionDialog.setVisible(true);
        
    }//GEN-LAST:event_conexionMenuItemActionPerformed

    private void guardarResultadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarResultadoMenuItemActionPerformed
        SqlQueryResult panel = (SqlQueryResult) this.sqlQueryResultTabbedPane.getSelectedComponent();
        panel.guardarLocalResult();
    }//GEN-LAST:event_guardarResultadoMenuItemActionPerformed

    private void pararButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararButtonActionPerformed
        SqlQueryResult panel = (SqlQueryResult) this.sqlQueryResultTabbedPane.getSelectedComponent();
        panel.cancelarLocalQuery();
    }//GEN-LAST:event_pararButtonActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        SqlQueryResult panel = (SqlQueryResult) this.sqlQueryResultTabbedPane.getSelectedComponent();
        panel.guardarLocalQuery();
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void acercaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaMenuItemActionPerformed
        JDialog dialog=new AcercaDialog(this,true);
        dialog.setVisible(true);
    }//GEN-LAST:event_acercaMenuItemActionPerformed

    private void guardarScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarScriptButtonActionPerformed
        guardarMenuItemActionPerformed(null);
    }//GEN-LAST:event_guardarScriptButtonActionPerformed

    private void duplicarConexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicarConexionMenuItemActionPerformed
        // TODO add your handling code here:
        int tabIndex = sqlQueryResultTabbedPane.getSelectedIndex();
        String title = sqlQueryResultTabbedPane.getTitleAt(tabIndex);
        SessionManager.NAME = title;
        SessionManager.CURRENTCONEXION.add(SessionManager.CURRENTCONEXION.get(tabIndex));
        addSqlQueryResultTab();
        
    }//GEN-LAST:event_duplicarConexionMenuItemActionPerformed

    private void guardarTablaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTablaButtonActionPerformed
        guardarResultadoMenuItemActionPerformed(evt);
    }//GEN-LAST:event_guardarTablaButtonActionPerformed

    private void conectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarButtonActionPerformed
        conexionMenuItemActionPerformed(evt);
    }//GEN-LAST:event_conectarButtonActionPerformed

    private void duplicarConexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicarConexionButtonActionPerformed
        duplicarConexionMenuItemActionPerformed(evt);
    }//GEN-LAST:event_duplicarConexionButtonActionPerformed

    protected void addSqlQueryResultTab() {
        int connexionIndex = SessionManager.CURRENTCONEXION.size() - 1;
        if (connexionIndex == 0) {
            JPanel empty = new JPanel();
            sqlQueryResultTabbedPane.add(empty, 0);
            sqlQueryResultTabbedPane.setTabComponentAt(0, new AddTabbedHeader(sqlQueryResultTabbedPane, this));
        }

        String title = SessionManager.NAME;
        SqlQueryResult tab = new SqlQueryResult(connexionIndex);
        sqlQueryResultTabbedPane.add(tab, connexionIndex);
        sqlQueryResultTabbedPane.setTitleAt(connexionIndex, title);
        sqlQueryResultTabbedPane.setTabComponentAt(connexionIndex, new ClosableTabbedHeader(sqlQueryResultTabbedPane));
        sqlQueryResultTabbedPane.setSelectedIndex(connexionIndex);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaMenuItem;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JButton conectarButton;
    private javax.swing.JMenuItem conexionMenuItem;
    private javax.swing.JButton duplicarConexionButton;
    private javax.swing.JMenuItem duplicarConexionMenuItem;
    private javax.swing.JButton ejecutarButton;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JMenuItem guardarResultadoMenuItem;
    private javax.swing.JButton guardarScriptButton;
    private javax.swing.JButton guardarTablaButton;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton pararButton;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JTabbedPane sqlQueryResultTabbedPane;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
